version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.3
    ports: 
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka:4.1.3
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_ZOOKEEPER_CONNECT: ${MY_IP}:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
