// Code generated by protoc-gen-go. DO NOT EDIT.
// source: leadpipe.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	leadpipe.proto

It has these top-level messages:
	Hit
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hit struct {
	VisitorID string  `protobuf:"bytes,1,opt,name=visitorID" json:"visitorID,omitempty"`
	Token     string  `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	User      string  `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Event     string  `protobuf:"bytes,4,opt,name=event" json:"event,omitempty"`
	Page      string  `protobuf:"bytes,5,opt,name=page" json:"page,omitempty"`
	Addr      string  `protobuf:"bytes,6,opt,name=addr" json:"addr,omitempty"`
	Agent     string  `protobuf:"bytes,7,opt,name=agent" json:"agent,omitempty"`
	Time      float64 `protobuf:"fixed64,8,opt,name=time" json:"time,omitempty"`
}

func (m *Hit) Reset()                    { *m = Hit{} }
func (m *Hit) String() string            { return proto.CompactTextString(m) }
func (*Hit) ProtoMessage()               {}
func (*Hit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Hit) GetVisitorID() string {
	if m != nil {
		return m.VisitorID
	}
	return ""
}

func (m *Hit) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Hit) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Hit) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Hit) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *Hit) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Hit) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *Hit) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Hit)(nil), "pb.Hit")
}

func init() { proto.RegisterFile("leadpipe.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x3d, 0x0e, 0xc2, 0x30,
	0x0c, 0x85, 0x95, 0xfe, 0x41, 0x33, 0x30, 0x44, 0x0c, 0x1e, 0x18, 0x2a, 0xa6, 0x4e, 0x2c, 0x5c,
	0x81, 0x01, 0xd6, 0xde, 0x20, 0x55, 0xad, 0x2a, 0x02, 0x9a, 0x28, 0x35, 0xbd, 0x19, 0xf7, 0x43,
	0xb6, 0x07, 0xb6, 0xf7, 0x3e, 0x7f, 0x6f, 0xb0, 0x3d, 0xbc, 0xd0, 0x4f, 0x29, 0x24, 0xbc, 0xa4,
	0x1c, 0x29, 0xba, 0x22, 0x8d, 0xe7, 0xaf, 0xb1, 0xe5, 0x3d, 0x90, 0x3b, 0xd9, 0x76, 0x0b, 0x6b,
	0xa0, 0x98, 0x1f, 0x37, 0x30, 0x9d, 0xe9, 0xdb, 0xe1, 0x0f, 0xdc, 0xd1, 0xd6, 0x14, 0x9f, 0xb8,
	0x40, 0x21, 0x17, 0x2d, 0xce, 0xd9, 0xea, 0xb3, 0x62, 0x86, 0x52, 0xa0, 0x64, 0x36, 0x71, 0xc3,
	0x85, 0xa0, 0x52, 0x53, 0x0a, 0x9b, 0xc9, 0xcf, 0x08, 0xb5, 0x9a, 0x9c, 0x99, 0xf9, 0x69, 0xca,
	0xd0, 0x28, 0xe3, 0xcc, 0x6b, 0x3f, 0xf3, 0x7a, 0xa7, 0x6b, 0x29, 0x6c, 0x52, 0x78, 0x23, 0xec,
	0x3b, 0xd3, 0x9b, 0x41, 0xf2, 0xd8, 0xc8, 0x0b, 0xd7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd,
	0x5c, 0x58, 0xd3, 0xd4, 0x00, 0x00, 0x00,
}
